name: 羽墨的博客
author: 182o.com
#baseurl: /182o.com
keywords: C,C++,Python,Java,github,git,jekyll,羽墨
description: 一个小白码农的日常
github: https://github.com/supercoderman
email: 286273384@qq.com


encoding: utf-8
#highlighter: rouge
markdown: kramdown
redcarpet:
  extensions: ["tables"]

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

port : 5000