title: Hi, I'm Kevin Taylor, welcome to my blog.
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "/SuperCoderMan.github.io" # the subpath of your site, e.g. /blog
url: "http://SuperCoderMan.github.io" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Kevin Taylor # add your name
author-img: Kevin-Taylor.jpg # add your photo
about-author: Our greatest glory is not in never falling, but in rising every time we fall. Always hungry to keep learning, keep going. # add description
email: 286273384@qq.com # your email
phone: 156****7748 # your pnone number
website: http://www.182o.com # you website

# Social link
twitter:    # add your Twitter handle
facebook:   # add your Facebook handle
github:     # add your Github handle
linkedin:   # add your Linkedin handle

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins_dir:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
